services:
  mysql:
    image: mysql:8
    container_name: patient-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patientdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uuser", "-ppassword" ]
      interval: 5s
      timeout: 5s
      retries: 10


  patient:
    build: ./patient
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/patientdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  gateway:
    build: ./gateway
    ports:
      - "8082:8082"
    depends_on:
      patient:
        condition: service_started

  front:
    build: ./front
    ports:
      - "8080:8080"
    depends_on:
      - gateway
      - patient