server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: patient-service
              uri: http://patient:8081
              predicates:
                - Path=/patients/**
              filters:
                - StripPrefix=0

            - id: front-service
              uri: http://front:8082
              predicates:
                - Path=/medilabo/**
              filters:
                - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG

