server:
  port: 8082

spring:
  security:
    user:
      name: admin
      password: password
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: patient-service
              uri: lb://patient
              predicates:
                - Path=/patients/**
              filters:
                - StripPrefix=0

            - id: notes-service
              uri: lb://notes
              predicates:
                - Path=/notes/**
              filters:
                - StripPrefix=0


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
