server:
  port: 8082

spring:
  main:
    lazy-initialization: true
  security:
    user:
      name: admin
      password: password
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: patient-service
              uri: lb://patient
              predicates:
                - Path=/patients/**
              filters:
                - StripPrefix=0

            - id: notes-service
              uri: lb://notes
              predicates:
                - Path=/notes/**
              filters:
                - StripPrefix=0

            - id : risk-service
              uri: lb://risk
              predicates:
                - Path=/risk/**
              filters:
                - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
